name = 'Swiper'
license = 'MIT'
licenselink = 'https://github.com/mmzeynalli/hugo-swiper/LICENSE'
description = 'Hugo theme for minimal gallery for artists'
homepage = 'https://github.com/mmzeynalli/hugo-swiper'

tags = ["responsive", "simple", "clean", "gallery", "minimalist", "swiper.js"]
features = [
  "responsive",
  "single-column",
  "gallery",
  "table-of-contents",
  "swiper.js",
  "favicon",
  "social-icons",
]
min_version = "0.116.0"

demosite = 'https://hugo-swiper-example.netlify.app'

# If the theme has a single author
[author]
name = 'Miradil Zeynalli'
homepage = 'https://mmzeynalli.dev'
